server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Proxy API do kontenera backendu
  location /api/ {
    proxy_pass http://api:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Authorization $http_authorization;
  }

  # SPA fallback (React Router)
  location / {
    try_files $uri $uri/ /index.html;
  }

  # PWA / cache statyków
  location ~* \.(?:js|css|woff2?|png|jpg|svg|webmanifest)$ {
    expires 7d;
    access_log off;
  }
}
